{
    'name': 'Biomedical Service Management',
    'version': '19.0.1.0.0',
    'summary': 'Service contract logic, internal expense tracking, automated service logs, and reminders for Biomedical Service.',
    'category': 'Services',
    'author': 'Elite Biomedical Service',
    'depends': [
        'sale',
        'purchase',
        'account',
        'hr_expense',
        'stock',
        'mail',
        'hr'
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/biomedical_expense_type_data.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'wizards/generate_service_log_wizard_views.xml',
        'wizards/expense_payment_wizard_views.xml',
        'wizards/service_invoice_wizard_views.xml',
        'views/service_log_views.xml',
        'views/sale_expense_views.xml',
        'views/service_config_views.xml',
        'views/sale_order_views.xml',
        'views/res_config_settings_views.xml',
        'report/service_log_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
